### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by abdallah96** [infomediadesign/sad-02-2022-project-v5#106]
Message is being sent even if it is not a match 
Ex: Julia wants to see only woman but Anna wants to see only boy, however Julia is able to send message to Anna while Anna cannot even see Julia on her profile

**Comment by PranavJ96** [comment]
How is the conversation getting started without a match
?

**Comment by abdallah96** [comment]
The user is being shown to the chatbox once liked

**Comment by PranavJ96** [comment]
The user is being shown the conversation only when they are matched. Checked the functionality. Closing the issue
