### ISSUE TITLE
Passsions and Which Pet do you like ? - Questionnaire

### ISSUE THREAD

**Issue by HarshiniJadav04** [infomediadesign/sad-02-2022-project-v5#81]
![566371e6-736f-4d31-a6f2-485cf248f9f4](https://user-images.githubusercontent.com/94150032/173238246-79abeef5-8a1b-41ab-84ce-19494a634149.jpg)
![image](https://user-images.githubusercontent.com/94150032/173238268-941593be-998a-4aa4-93b5-69b939f892e1.png)

Please check these 2 images for more infomation. // logged in from Shubham@gmail.com
There is a lag and in Passions unable to click other options

**Comment by PranavJ96** [comment]
Issue Rsolved
